services:
  user_service:
    build:
      context: ../UserService # Sørg for, at hele UserService-projektet er inkluderet
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - shared-network

  auth_service:
    build:
      context: ../../AuthService/AuthService # Sørg for, at hele projektet er inkluderet
      dockerfile: Dockerfile
    ports:
      - "5162:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Vault__Address: "https://vault_dev:8201"
      UserServiceUrl: "http://user_service:8080" # Brug UserService's containernavn og port
    depends_on:
      - vault_dev
    networks:
      - shared-network

  vault_dev:
    image: hashicorp/vault:latest
    restart: on-failure:10
    ports:
      - "8201:8201"
    environment:
      VAULT_ADDR: "https://0.0.0.0:8201"
      VAULT_LOCAL_CONFIG: >
        {"listener": [{"tcp":{"address": "0.0.0.0:8201",
        "tls_disable": "0", "tls_cert_file":"/data/cert.pem",
        "tls_key_file":"/data/key.pem"}}],
        "default_lease_ttl": "168h", "max_lease_ttl": "720h",
        "ui": true}
        "api_addr": "https://vault_dev:8201"}
      VAULT_DEV_ROOT_TOKEN_ID: "00000000-0000-0000-0000-000000000000"
      VAULT_TOKEN: "00000000-0000-0000-0000-000000000000"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-volume:/data
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: 'server -dev -dev-root-token-id="00000000-0000-0000-0000-00000000"'
    networks:
      - shared-network

  vault-init:
    image: hashicorp/vault:latest
    command: sh "/app/vault_init.sh"
    depends_on:
      - vault_dev
    healthcheck:
      retries: 5
    volumes:
      - ./vault-init/vault_init.sh:/app/vault_init.sh
    networks:
      - shared-network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - shared-network

volumes:
  mongodb_data:
  vault-volume:
  external: false

networks:
  shared-network:
    external: false
    driver: bridge
