services:
  user_service:
    build:
      context: ../UserService # Sørg for, at hele UserService-projektet er inkluderet
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Vault__Address: "https://vaulthost:8201"
    depends_on:
    - vault-init
    networks:
      - shared-network

  auth_service:
    build:
      context: ../../AuthService/AuthService # Sørg for, at hele projektet er inkluderet
      dockerfile: Dockerfile
    restart: on-failure:10
    ports:
      - "5162:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Vault__Address: "https://vaulthost:8201"
      UserServiceUrl: "http://user_service:8080" # Brug UserService's containernavn og port
    depends_on:
      - vault-init
      - user_service
    healthcheck:
      retries: 5
    networks:
      - shared-network

  vaulthost:
    image: hashicorp/vault:latest
    container_name: vaulthost
    restart: on-failure:10
    ports:
      - "8201:8201"
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8201'
      VAULT_API_ADDR: 'http://0.0.0.0:8200'
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8201", "tls_disable": "0", "tls_cert_file":"/data/cert.pem", "tls_key_file":"/data/key.pem"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
      VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
      VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data:/data
      - vaultdataVOL:/var/lib/vault:rw
    healthcheck:
      retries: 5
    networks:
      - shared-network
    command: server -dev -dev-root-token-id="00000000-0000-0000-0000-000000000000"

  vault-init:
    image: hashicorp/vault:latest
    command: sh "/app/vault_init.sh"
    depends_on:
      - vaulthost
    healthcheck:
      retries: 5
    volumes:
      - ./vault-init/vault_init.sh:/app/vault_init.sh
    networks:
      - shared-network
    
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - shared-network

volumes:
  mongodb_data:
  vaultdataVOL:
    external: false

networks:
  shared-network:
    external: false
    driver: bridge
